import * as React from 'react';
import {createRoot} from 'react-dom/client';
import {Branchflow, type BranchflowStep} from '../registry/default/branchflow';
import {EvidenceLens} from '../registry/default/evidence-lens';
import {ActionHalo} from '../registry/default/action-halo';
import './style.css';
const examples={
 branchflow:`import { Branchflow } from "@/components/ui/branchflow"\n\n<Branchflow steps={[\n  { id: "review", label: "Review evidence", status: "current",\n    detail: "Check the remaining signals.",\n    branches: [{ label: "Ask a specialist", tone: "warning" }] },\n  { id: "decide", label: "Make decision", status: "upcoming" }\n]} />`,
 'evidence-lens':`import { EvidenceLens } from "@/components/ui/evidence-lens"\n\n<EvidenceLens items={[\n  { id: "support", label: "Support", value: 54, note: "Recent interviews." },\n  { id: "conflict", label: "Conflict", value: 28, note: "Older research." }\n]} conclusion="Review the conflicting evidence before deciding." />`,
 'action-halo':`import { ActionHalo } from "@/components/ui/action-halo"\n\n<ActionHalo actions={[\n  { id: "explain", label: "Explain", onSelect: () => explain() },\n  { id: "approve", label: "Approve", onSelect: () => approve() }\n]} />`
};
function Install({name}:{name:string}){
 const [state,setState]=React.useState('Copy');const command=`npx shadcn@latest add ${window.location.origin}/r/${name}.json`;
 return <div className="mini-install"><code title={command}>{command}</code><button type="button" aria-label={`Copy ${name} install command`} onClick={async()=>{try{await navigator.clipboard.writeText(command);setState('Copied')}catch{setState('Select command to copy')}}}>{state}</button></div>
}
function App(){
 const [dark,setDark]=React.useState(false),[phase,setPhase]=React.useState(1),[empty,setEmpty]=React.useState(false),[outcome,setOutcome]=React.useState('Choose an action to see its callback.');
 const steps:BranchflowStep[]=['Collect context','Review evidence','Make decision','Publish outcome'].map((label,i)=>({id:String(i),label,status:i<phase?'complete':i===phase?'current':'upcoming',detail:i===phase?'This is the step currently being worked on.':undefined,branches:i===1?[{label:'Ask specialist',tone:'neutral'},{label:'Run another check',tone:'warning'}]:undefined}));
 const items=[{id:'support',label:'Signals support',value:54,note:'Illustrative data: recent customer interviews point toward the same need.'},{id:'conflict',label:'Signals conflict',value:28,note:'Illustrative data: conflicting signals come from an older dataset.'},{id:'unknown',label:'Still unknown',value:18,note:'Illustrative data: two assumptions still need validation.'}];
 React.useEffect(()=>{document.body.classList.toggle('theme-dark',dark)},[dark]);
 return <><div className="wrap"><nav><a className="logo" href="#" style={{color:'inherit',textDecoration:'none'}}><span className="mark"/>ORBITO UI</a><div className="navlinks"><a href="#components">Components</a><a href="#setup">Setup</a><a className="github-link" href="https://github.com/abheeyeee/orbito-ui" target="_blank" rel="noopener noreferrer" aria-label="Star Orbito UI on GitHub">☆ GitHub</a><button type="button" className="pill" onClick={()=>setDark(v=>!v)}>{dark?'Light':'Dark'}</button></div></nav><main>
 <section className="hero"><div><h1>Make complexity<br/><i>legible.</i></h1><p className="lead">React components for products where people compare evidence, follow branching work, and choose what happens next.</p><Install name="branchflow"/></div><div className="orbit-stage" aria-hidden="true"><div className="orbit o1"/><div className="orbit o2"/><div className="core">Clarity<br/>at the core</div><div className="planet p1">Compare</div><div className="planet p2">Decide</div><div className="planet p3">Act</div></div></section>
 <section id="components"><div className="intro"><div><div className="section-kicker">The first orbit</div><h2>Three components.<br/>One clear system.</h2></div><div className="count">03</div></div>
 {(['branchflow','evidence-lens','action-halo'] as const).map((name,i)=><React.Fragment key={name}><article className="component"><div><div className="comp-num">0{i+1} / {['WORKFLOW','COMPARISON','ACTIONS'][i]}</div><h3>{['Branchflow','Evidence Lens','Action Halo'][i]}</h3><p>{['A readable progress list with optional branch labels. Change the active step to follow the workflow.','Inspect the context behind each signal. Use the buttons with a pointer, touch, or keyboard.','A compact action launcher with a curved panel. Arrow keys navigate, Escape closes, and focus returns to the trigger.'][i]}</p><Install name={name}/><div className="tags"><span className="tag">React + TypeScript</span><span className="tag">Tailwind 4</span></div></div><div className="preview"><span className="preview-label">Actual React component · sample data</span><div className="demo-body">{i===0?<><Branchflow steps={steps}/><div className="demo-controls"><button onClick={()=>setPhase(p=>(p+1)%5)}>Advance step</button><button onClick={()=>setPhase(0)}>Reset</button></div></>:i===1?<><EvidenceLens items={empty?[]:items} conclusion="Review uncertainty before deciding."/><div className="demo-controls"><button onClick={()=>setEmpty(v=>!v)}>{empty?'Restore data':'Show empty state'}</button></div></>:<><div className="halo-demo"><ActionHalo actions={['Explain','Share','Approve'].map(label=>({id:label,label,onSelect:()=>setOutcome(`${label} selected. Your application handles the actual action.`)}))}/></div><p role="status" className="text-center text-sm">{outcome}</p></>}</div></div></article><div className="docs"><details><summary>Usage and API — {name}</summary><pre><code>{examples[name]}</code></pre><p className="my-4 text-sm">{i===0?'steps: BranchflowStep[]. Each step needs a unique id, label and status (complete, current, upcoming or blocked). Optional detail and branches with neutral, positive or warning tone.':i===1?'items: EvidenceItem[]. Each item needs a unique id, label and nonnegative value. Optional note and CSS color. Invalid or negative values display as zero. Optional conclusion.':'actions: HaloAction[]. Each action needs a unique id, label and onSelect callback. Optional icon and disabled. Optional trigger label. Empty actions disable the trigger.'} All components accept className. Supply descriptive labels and application-specific content.</p></details></div></React.Fragment>)}
 </section><section id="setup" className="docs rule"><h2>Start with your app.</h2><p className="my-6">Use React 18 or 19, Tailwind CSS 4, and a configured shadcn project. Initialize shadcn, then copy a component’s install command above.</p><pre><code>npx shadcn@latest init</code></pre><p className="my-6">The components use your shadcn semantic colors: background, foreground, card, card-foreground, muted, muted-foreground and border. No extra icon or animation libraries are required. The source is copied into your project for you to edit.</p><p>Action Halo is a nonmodal menu. Its callbacks belong to your application; it does not send messages, approve records, or connect services itself.</p></section>
 </main><footer className="footer rule"><div className="logo">ORBITO UI</div><div className="fine">Created by Abhinav Singh · 2026<br/>MIT licensed · v0.1.0</div></footer></div></>
}
createRoot(document.getElementById('root')!).render(<App/>);
